# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuckNum8' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LuckNum8
pod 'Toast-Swift', '~> 3.0.1'
  pod 'PMAlertController'
  target 'LuckNum8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LuckNum8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
